"""Tabelas de auditoria legislativa independentes das regras fiscais."""

from sqlalchemy import (
    CheckConstraint, Column, Date, DateTime, ForeignKey, Identity, Index,
    Integer, MetaData, Numeric, String, Table, Text, UniqueConstraint, func,
)

metadata = MetaData()

atos_legislativos = Table(
    "atos_legislativos", metadata,
    Column("id", Integer, Identity(), primary_key=True),
    Column("tipo_ato", String(80), nullable=False),
    Column("numero", String(40), nullable=False),
    Column("ano", Integer, nullable=False),
    Column("data_ato", Date),
    Column("data_descoberta", Date),
    Column("data_ato_documento", Date),
    Column("data_publicacao", Date),
    Column("divergencia_data", String(3), nullable=False, server_default="NAO"),
    Column("advertencia_data", Text),
    Column("titulo", Text, nullable=False),
    Column("ementa", Text),
    Column("url_descoberta", Text, nullable=False),
    Column("url_texto_oficial", Text),
    Column("texto_original", Text),
    Column("texto_limpo", Text),
    Column("hash_conteudo", String(64)),
    Column("fonte", Text, nullable=False),
    Column("data_coleta", DateTime(timezone=True), server_default=func.now(), nullable=False),
    Column("data_ultima_verificacao", DateTime(timezone=True), server_default=func.now(), nullable=False),
    Column("status", String(12), nullable=False),
    Column("relevancia", String(5), nullable=False),
    Column("motivos_relevancia", Text, nullable=False),
    Column("relevancia_ncm", String(11), nullable=False, server_default="SEM_INDICIO"),
    Column("motivos_relevancia_ncm", Text, nullable=False, server_default=""),
    Column("quantidade_ncms_texto", Integer, nullable=False, server_default="0"),
    Column("possui_ncm_explicito", String(3), nullable=False, server_default="NAO"),
    Column("possui_prefixo_ncm", String(3), nullable=False, server_default="NAO"),
    Column("possui_termo_material_icms", String(3), nullable=False, server_default="NAO"),
    Column("texto_consolidado", String(3), nullable=False, server_default="NAO"),
    Column("erro_coleta", Text),
    UniqueConstraint("tipo_ato", "numero", "ano", name="uq_ato_tipo_numero_ano"),
    CheckConstraint("status IN ('NOVO', 'PROCESSADO', 'ERRO', 'IGNORADO')", name="ck_ato_status"),
    CheckConstraint("relevancia IN ('ALTA', 'MEDIA', 'BAIXA')", name="ck_ato_relevancia"),
    CheckConstraint("divergencia_data IN ('SIM', 'NAO')", name="ck_ato_divergencia_data"),
    CheckConstraint("relevancia_ncm IN ('MUITO_ALTA', 'ALTA', 'MEDIA', 'BAIXA', 'SEM_INDICIO')", name="ck_ato_relevancia_ncm"),
)
Index("ix_atos_status", atos_legislativos.c.status)
Index("ix_atos_verificacao", atos_legislativos.c.data_ultima_verificacao)

versoes_ato = Table(
    "versoes_ato", metadata,
    Column("id", Integer, Identity(), primary_key=True),
    Column("ato_id", Integer, ForeignKey("atos_legislativos.id", ondelete="RESTRICT"), nullable=False),
    Column("hash_conteudo", String(64), nullable=False),
    Column("texto_original", Text, nullable=False),
    Column("texto_limpo", Text, nullable=False),
    Column("url_origem", Text),
    Column("texto_consolidado", String(3), nullable=False, server_default="NAO"),
    Column("data_coleta", DateTime(timezone=True), server_default=func.now(), nullable=False),
)
Index("ix_versoes_ato_id", versoes_ato.c.ato_id)

monitoramento_legislativo = Table(
    "monitoramento_legislativo", metadata,
    Column("id", Integer, Identity(), primary_key=True),
    Column("data_execucao", DateTime(timezone=True), server_default=func.now(), nullable=False),
    Column("fonte", Text, nullable=False),
    Column("quantidade_encontrada", Integer, nullable=False),
    Column("quantidade_nova", Integer, nullable=False),
    Column("quantidade_atualizada", Integer, nullable=False),
    Column("quantidade_ignorados", Integer, nullable=False),
    Column("quantidade_erros", Integer, nullable=False),
    Column("mensagem", Text),
)
Index("ix_monitoramento_execucao", monitoramento_legislativo.c.data_execucao)

# Resultados da Fase 2 são deliberadamente isolados das tabelas fiscais.
processamentos_extracao = Table(
    "processamentos_extracao", metadata,
    Column("id", Integer, Identity(), primary_key=True),
    Column("ato_id", Integer, ForeignKey("atos_legislativos.id", ondelete="RESTRICT"), nullable=False),
    Column("versao_ato_id", Integer, ForeignKey("versoes_ato.id", ondelete="RESTRICT"), nullable=False),
    Column("extrator_versao", String(30), nullable=False),
    Column("status", String(10), nullable=False, server_default="PENDENTE"),
    Column("data_extracao", DateTime(timezone=True), server_default=func.now(), nullable=False),
    UniqueConstraint("versao_ato_id", "extrator_versao", name="uq_processamento_versao_extrator"),
    CheckConstraint("status IN ('PENDENTE', 'COMPLETO', 'FALHOU')", name="ck_processamento_status"),
)

regras_extraidas = Table(
    "regras_extraidas", metadata,
    Column("id", Integer, Identity(), primary_key=True),
    Column("ato_id", Integer, ForeignKey("atos_legislativos.id", ondelete="RESTRICT"), nullable=False),
    Column("versao_ato_id", Integer, ForeignKey("versoes_ato.id", ondelete="RESTRICT"), nullable=False),
    Column("processamento_id", Integer, ForeignKey("processamentos_extracao.id", ondelete="RESTRICT"), nullable=False),
    Column("chave_extracao", String(64), nullable=False),
    Column("tipo_regra", String(32), nullable=False),
    Column("acao_legislativa", String(20), nullable=False),
    Column("ncm_chave", String(8)),
    Column("ncm_original", String(20)),
    Column("descricao_proxima_ncm", Text),
    Column("tipo_correspondencia", String(7)),
    Column("descricao_legal", Text),
    Column("descricao_resumida", Text),
    Column("aliquota_icms", Numeric(9, 4)),
    Column("percentual_reducao_bc", Numeric(9, 4)),
    Column("carga_efetiva", Numeric(9, 4)),
    Column("credito_outorgado_percentual", Numeric(9, 4)),
    Column("tipo_beneficio", String(32)),
    Column("anexo", String(30)),
    Column("artigo", String(30)),
    Column("paragrafo", String(30)),
    Column("inciso", String(30)),
    Column("alinea", String(30)),
    Column("item", String(30)),
    Column("vigencia_inicio", Date),
    Column("vigencia_fim", Date),
    Column("condicoes_texto", Text),
    Column("norma_alterada", Text),
    Column("trecho_origem", Text, nullable=False),
    Column("inicio_trecho", Integer, nullable=False),
    Column("fim_trecho", Integer, nullable=False),
    Column("confianca", String(5), nullable=False),
    Column("status_revisao", String(10), nullable=False, server_default="PENDENTE"),
    Column("escopo_fiscal", String(24), nullable=False, server_default="INDETERMINADO"),
    Column("elegivel_consolidacao", String(3), nullable=False, server_default="NAO"),
    Column("motivo_elegibilidade", Text, nullable=False, server_default="Classificação de escopo pendente."),
    Column("papel_dispositivo", String(24), nullable=False, server_default="INDETERMINADO"),
    Column("grupo_regra_id", String(32)),
    Column("elegivel_consulta_ncm", String(3), nullable=False, server_default="NAO"),
    Column("status_vinculo_ncm", String(24), nullable=False, server_default="NAO_AVALIADO"),
    Column("motivo_consulta_ncm", Text, nullable=False, server_default="Vínculo com NCM não avaliado."),
    Column("motivos_confianca", Text, nullable=False),
    Column("alertas", Text),
    Column("data_extracao", DateTime(timezone=True), server_default=func.now(), nullable=False),
    Column("extrator_versao", String(30), nullable=False),
    UniqueConstraint("versao_ato_id", "extrator_versao", "chave_extracao", name="uq_regra_versao_extrator_chave"),
    CheckConstraint("tipo_correspondencia IS NULL OR tipo_correspondencia IN ('EXATO', 'PREFIXO')", name="ck_regra_correspondencia"),
    CheckConstraint("confianca IN ('ALTA', 'MEDIA', 'BAIXA')", name="ck_regra_confianca"),
    CheckConstraint("status_revisao IN ('PENDENTE', 'VALIDADO', 'DESCARTADO')", name="ck_regra_revisao"),
    CheckConstraint("escopo_fiscal IN ('ALIQUOTA_BENEFICIO', 'PAUTA_PRECO', 'CREDITO_TRIBUTARIO', 'PROCEDIMENTO', 'ADMINISTRATIVO', 'OUTRO', 'INDETERMINADO')", name="ck_regra_escopo_fiscal"),
    CheckConstraint("elegivel_consolidacao IN ('SIM', 'NAO')", name="ck_regra_elegibilidade"),
    CheckConstraint("papel_dispositivo IN ('REGRA_MATERIAL', 'ABRANGENCIA', 'BENEFICIARIO', 'CALCULO', 'UTILIZACAO', 'CONDICAO', 'VEDACAO', 'EXCECAO', 'CONSEQUENCIA', 'PROCEDIMENTO', 'REFERENCIA', 'INDETERMINADO')", name="ck_regra_papel_dispositivo"),
    CheckConstraint("elegivel_consulta_ncm IN ('SIM', 'NAO')", name="ck_regra_consulta_ncm"),
    CheckConstraint("status_vinculo_ncm IN ('NCM_EXPLICITO', 'PENDENTE_VINCULO_NCM', 'SEM_VINCULO_NCM', 'NAO_AVALIADO')", name="ck_regra_status_vinculo_ncm"),
)
Index("ix_regras_extraidas_status", regras_extraidas.c.status_revisao)
Index("ix_regras_extraidas_ato", regras_extraidas.c.ato_id)
Index("ix_regras_extraidas_grupo", regras_extraidas.c.grupo_regra_id)

evidencias_extracao = Table(
    "evidencias_extracao", metadata,
    Column("id", Integer, Identity(), primary_key=True),
    Column("regra_extraida_id", Integer, ForeignKey("regras_extraidas.id", ondelete="RESTRICT"), nullable=False),
    Column("tipo_evidencia", String(32), nullable=False),
    Column("valor_extraido", Text, nullable=False),
    Column("texto_origem", Text, nullable=False),
    Column("posicao_inicio", Integer, nullable=False),
    Column("posicao_fim", Integer, nullable=False),
    Column("confianca", String(5), nullable=False),
    Column("metodo", String(50), nullable=False),
)
Index("ix_evidencias_regra", evidencias_extracao.c.regra_extraida_id)

# Fase 3: projeções revisáveis. Nenhuma destas tabelas integra o motor fiscal.
regras_consolidadas = Table(
    "regras_consolidadas", metadata,
    Column("id", Integer, Identity(), primary_key=True),
    Column("chave_consolidacao", String(64), nullable=False),
    Column("grupo_regra_id", String(32)),
    Column("tipo_regra", String(32), nullable=False),
    Column("ncm_chave", String(8)),
    Column("tipo_correspondencia", String(7)),
    Column("descricao_legal", Text),
    Column("aliquota_icms", Numeric(9, 4)),
    Column("percentual_reducao_bc", Numeric(9, 4)),
    Column("carga_efetiva", Numeric(9, 4)),
    Column("credito_outorgado_percentual", Numeric(9, 4)),
    Column("tipo_beneficio", String(32)),
    Column("norma_base", Text),
    Column("anexo", String(30)),
    Column("artigo", String(30)),
    Column("paragrafo", String(30)),
    Column("inciso", String(30)),
    Column("alinea", String(30)),
    Column("item", String(30)),
    Column("condicoes_texto", Text),
    Column("complementos_json", Text),
    Column("vigencia_inicio", Date),
    Column("vigencia_fim", Date),
    Column("status_regra", String(15), nullable=False),
    Column("status_validacao", String(10), nullable=False, server_default="PENDENTE"),
    Column("confianca", String(5), nullable=False),
    Column("regra_origem_id", Integer, ForeignKey("regras_extraidas.id", ondelete="RESTRICT"), nullable=False),
    Column("ato_origem_id", Integer, ForeignKey("atos_legislativos.id", ondelete="RESTRICT"), nullable=False),
    Column("regra_substituida_id", Integer, ForeignKey("regras_consolidadas.id", ondelete="RESTRICT")),
    Column("regra_anterior_id", Integer, ForeignKey("regras_consolidadas.id", ondelete="RESTRICT")),
    Column("relacao_regra", String(15), nullable=False, server_default="INDETERMINADA"),
    Column("motivo_consolidacao", Text, nullable=False),
    Column("alertas", Text),
    Column("origens_equivalentes", Text, nullable=False, server_default="[]"),
    Column("data_consolidacao", DateTime(timezone=True), server_default=func.now(), nullable=False),
    Column("consolidador_versao", String(30), nullable=False),
    UniqueConstraint("regra_origem_id", "consolidador_versao", name="uq_consolidada_origem_versao"),
    CheckConstraint("status_regra IN ('VIGENTE', 'FUTURA', 'SUBSTITUIDA', 'REVOGADA', 'CONFLITO', 'INDETERMINADA')", name="ck_consolidada_status"),
    CheckConstraint("status_validacao IN ('PENDENTE', 'VALIDADA', 'DESCARTADA')", name="ck_consolidada_validacao"),
    CheckConstraint("confianca IN ('ALTA', 'MEDIA', 'BAIXA')", name="ck_consolidada_confianca"),
    CheckConstraint("relacao_regra IN ('GERAL', 'ESPECIFICA', 'EXCECAO', 'INDETERMINADA')", name="ck_consolidada_relacao"),
)
Index("ix_consolidadas_chave", regras_consolidadas.c.chave_consolidacao)
Index("ix_consolidadas_status", regras_consolidadas.c.status_regra)
Index("ix_consolidadas_ato", regras_consolidadas.c.ato_origem_id)

relacoes_regras = Table(
    "relacoes_regras", metadata,
    Column("id", Integer, Identity(), primary_key=True),
    Column("regra_origem_id", Integer, ForeignKey("regras_consolidadas.id", ondelete="RESTRICT"), nullable=False),
    Column("regra_destino_id", Integer, ForeignKey("regras_consolidadas.id", ondelete="RESTRICT"), nullable=False),
    Column("tipo_relacao", String(20), nullable=False),
    Column("motivo", Text, nullable=False),
    Column("confianca", String(5), nullable=False),
    Column("consolidador_versao", String(30), nullable=False),
    Column("data_criacao", DateTime(timezone=True), server_default=func.now(), nullable=False),
    UniqueConstraint("regra_origem_id", "regra_destino_id", "tipo_relacao", "consolidador_versao", name="uq_relacao_consolidada"),
    CheckConstraint("tipo_relacao IN ('ALTERA', 'SUBSTITUI', 'REVOGA', 'PRORROGA', 'RENOVA', 'EXCECAO_DE', 'ESPECIFICA_DE', 'DUPLICADA_DE', 'CONFLITA_COM')", name="ck_relacao_tipo"),
    CheckConstraint("confianca IN ('ALTA', 'MEDIA', 'BAIXA')", name="ck_relacao_confianca"),
)
Index("ix_relacoes_destino", relacoes_regras.c.regra_destino_id)
